### ISSUE TITLE
Babel helpers are being inlined in ES5 outputs

### ISSUE THREAD

**Issue by robbiepitts** [glimmerjs/glimmer-build#37]
If you look at the build output for ES5 you'll see that function declarations for babel helpers (like `classCallCheck`) are at the top of almost every file. We may be best served with an approach like the [transform-runtime plugin](https://babeljs.io/docs/plugins/transform-runtime/).

**Comment by dgeb** [comment]
@robbiepitts this was a deliberate decision (the rationale is explained in #33).

**Comment by robbiepitts** [comment]
👍
