### ISSUE TITLE
broccoli-typescript-compiler@next doesn't exist

### ISSUE THREAD

**Issue by jayphelps** [glimmerjs/glimmer-build#47]
broccoli-typescript-compiler semver [is set to `next`](https://github.com/glimmerjs/glimmer-build/commit/35c3ff0b0e8afe698a7cb212d33184168b70a2d2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R59
), but that package currently has no `next` tag so if you're using npm to install, [it will error saying "No compatible version found"](https://github.com/glimmerjs/glimmer-vm/issues/561#issuecomment-314806667). It does have a `beta` though, should it be changed to that?

```
'dist-tags': { latest: '2.1.0', beta: '2.0.0-beta.2' }
```

It's unclear how this worked when the yarn lockfile was updated? My best guess is that project had a `next` tag but it was later deleted/renamed.

Cc/ @piotrpalek in case you care

**Comment by rwjblue** [comment]
confirm, the tag was removed

**Comment by rwjblue** [comment]
The fix is to either add the tag back, or update to the specific version in our package.json and update the lock file.
